# Problem
# In a weighted alphabet, every symbol is assigned a positive real number called a weight. A string formed from a weighted alphabet is called a weighted string, and its weight is equal to the sum of the weights of its symbols.
# The standard weight assigned to each member of the 20-symbol amino acid alphabet is the monoisotopic mass of the corresponding amino acid.
# Given: A protein string P
# of length at most 1000 aa.
# Return: The total weight of P
# . Consult the monoisotopic mass table.
# Sample Dataset
# SKADYEK
# Sample Output
# 821.392
import re
dataset = 'MCVEALRDKCWCNYNLSTTGINEKMYELEDHEMQRIHPGPHKQSYYMNIDALCSRYFEIHSPIRADNHANKRCETFTHPDRVMPMRACFWEAPVCCRGQQTDCITWGHANEFHGNTKRLFETFWNHWCSDDYATTMGSSFYSNINPFLRLFTIAYRTMSGPAMAYLVYSEKSQHNAFRWEGILEYKVWCDFMNDWAWITCGQNQWAIASCCENFLCGFHGAAGGQFWKNELKFVCGCVWLWKFYHWDMPSPWVDYYENPPPMQGAVETAEIPHDGWHNNSISLTCDHGPGSKIRHLPFWFIMNAAPHFRHFWHIGNHHYMWLDWMSGPPFLHCCAPLRGKPIINARYELTQIKTAHAIMWHTQMYVAYFTAIPMIVMAHYPPNGDSDYKYIMYGWYYGANNCPQHIASNNHVHVSRLVPGKDRPMVWNSGNANFCAIQDMARHGITSQRLEYMTCCKQSTYNMNSKLTGGFVNQPTAGRANDVFQGANPECEPAHPCNPREDTRAPSWFSMSKMPQWPFLPCCIKRTPMKPVAAIQPAICDRCVWLGAPFMAWYVYDVFTCFGDSRGFKDRVCRYFMDRGTPINYTTIRDANWQILHVDTNRRNRYLFTKCGLCHCRHMYHSGGKMCWSNPSHSTVYIGFIPKLPEMSQTATMTPVDIFFSEHPRCTHIHQRCIIEMACCGFPWQMISHSSLEPMTSGKQANYDADMKEYWHWPIENKDYRVIYDCTYEVIKTSTFITLSYQSNQMNCKLPRVDHMRGKNVFPNWSLGFYPILDKVGNDQEKPFTWFNPDNYYGQTWEASGNTFLFKCKFSKWIIYHPICQVCMDEGPAWDRRVTDCCYYLDMDMMSSFGRRLQHHHVLSVYNCMQDLGYSIYVVLQDLGLIWSWAKLNYKTGLYCMAGYAENPAFLCSRADMENVFAIWRSYRGVNRQSMGSPRVWYLMARDQPKKGVVP'
input_file = open('Monoisotopic mass table.txt')
init_string = input_file.read()
string_list = re.split(r'\n', init_string)
dict_mass = {}
total_weight = 0
for item in string_list:
    dict_mass[item[0]] = float(re.search(r'\d+\.\d+', item).group(0))
for amino_acid in dataset:
    total_weight += dict_mass[amino_acid]
print(total_weight)